# Generated by Django 4.2.30 on 2026-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0004_student_department_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
