# Generated by Django 4.2.30 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_generator", "0005_student_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
