# Generated by Django 4.2.30 on 2026-08-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0006_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
