# Generated by Django 4.2.30 on 2026-08-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0007_internship_department_internship_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='log',
            name='daily_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='log',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
