# Generated by Django 4.2.30 on 2026-08-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0008_log_achievements_log_daily_entries_log_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='log',
            name='department_unit',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='log',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='log',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='report_generator.internship'),
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='programme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='log',
            name='student_index_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='log',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
