# Generated by Django 4.2.30 on 2026-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0009_log_company_name_log_department_log_department_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teams_id',
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
