# Generated by Django 4.2.30 on 2026-08-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0011_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='supervisor_email',
        ),
        migrations.AddField(
            model_name='student',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='students', to='report_generator.supervisor'),
        ),
    ]
