# Generated by Django 4.2.30 on 2026-08-06 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0012_remove_student_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('general_comments', models.TextField(blank=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('signature', models.TextField(blank=True)),
                ('appraisal_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal', to='report_generator.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='report_generator.supervisor')),
            ],
        ),
    ]
