# Generated by Django 4.2.30 on 2026-08-06 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


INITIAL_COMPANY_NAMES = [
    "Ghana Revenue Authority",
    "MTN Ghana",
    "Vodafone Ghana",
    "Bank of Ghana",
    "Ghana Water Company",
    "Electricity Company of Ghana",
    "KPMG Ghana",
    "Ecobank Ghana",
    "Stanbic Bank Ghana",
    "Tullow Oil Ghana",
    "Tech Innovation Ltd",
    "Digital Solutions Inc",
    "Cloud Services Ltd",
    "Enterprise Solutions",
    "Tech Innovations",
    "Stanbic Bank",
    "Electricity Company",
]


def seed_companies(apps, schema_editor):
    Company = apps.get_model("report_generator", "Company")
    for name in INITIAL_COMPANY_NAMES:
        normalized = (name or "").strip()
        if not normalized:
            continue
        Company.objects.get_or_create(name=normalized, defaults={"is_active": True})


def unseed_companies(apps, schema_editor):
    Company = apps.get_model("report_generator", "Company")
    Company.objects.filter(name__in=INITIAL_COMPANY_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_generator', '0013_appraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_companies, unseed_companies),
    ]
