from django.urls import path

from .views import (
    AdminAppraisalDetailView,
    AdminDashboardView,
    AdminCompanyDetailView,
    AdminCompanyListCreateView,
    AdminCompanyRequestDetailView,
    AdminCompanyRequestListView,
    AdminReportDownloadView,
    AdminReportDetailView,
    AdminReportPreviewView,
    AdminReportsIndexView,
    AdminStudentDetailView,
    AdminStudentsView,
    AuthLoginView,
    AuthRegisterView,
    ChangePasswordView,
    CurrentUserProfileView,
    GenerateReportView,
    HealthCheckView,
    NotificationListView,
    NotificationMarkReadView,
    NotificationMarkAllReadView,
    NotificationSummaryView,
    StudentDashboardView,
    StudentCompanyListView,
    StudentCompanyRequestListCreateView,
    StudentGenerateReportView,
    StudentInternshipView,
    StudentReportsView,
    StudentReportUploadView,
    StudentFeedbackView,
    StudentLogDetailView,
    StudentLogView,
    StudentProfileView,
    StudentReportDraftView,
    SupervisorAppraisalDetailView,
    SupervisorAppraisalListView,
    SupervisorAssignedAppraisalStudentsView,
    SupervisorBulkStatusView,
    SupervisorLogDetailView,
    SupervisorLogsView,
    SupervisorReportsView,
    SupervisorStudentsView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("generate-report/", GenerateReportView.as_view(), name="generate-report"),
    path("auth/register/", AuthRegisterView.as_view(), name="auth-register"),
    path("auth/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="auth-change-password"),
    path("auth/me/", CurrentUserProfileView.as_view(), name="auth-me"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/summary/", NotificationSummaryView.as_view(), name="notifications-summary"),
    path("notifications/<uuid:activity_id>/read/", NotificationMarkReadView.as_view(), name="notifications-read"),
    path("notifications/mark-all-read/", NotificationMarkAllReadView.as_view(), name="notifications-mark-all-read"),
    path("student/profile/", StudentProfileView.as_view(), name="student-profile"),
    path("student/dashboard/", StudentDashboardView.as_view(), name="student-dashboard"),
    path("student/companies/", StudentCompanyListView.as_view(), name="student-companies"),
    path("student/company-requests/", StudentCompanyRequestListCreateView.as_view(), name="student-company-requests"),
    path("student/reports/", StudentReportsView.as_view(), name="student-reports"),
    path("student/internships/", StudentInternshipView.as_view(), name="student-internships"),
    path("student/logs/", StudentLogView.as_view(), name="student-logs"),
    path("student/logs/<uuid:log_id>/", StudentLogDetailView.as_view(), name="student-log-detail"),
    path("student/feedbacks/", StudentFeedbackView.as_view(), name="student-feedbacks"),
    path("student/report-draft/", StudentReportDraftView.as_view(), name="student-report-draft"),
    path("student/generate-report/", StudentGenerateReportView.as_view(), name="student-generate-report"),
    path("student/reports/upload/", StudentReportUploadView.as_view(), name="student-report-upload"),
    path("supervisor/students/", SupervisorStudentsView.as_view(), name="supervisor-students"),
    path("supervisor/appraisal-students/", SupervisorAssignedAppraisalStudentsView.as_view(), name="supervisor-appraisal-students"),
    path("supervisor/logs/", SupervisorLogsView.as_view(), name="supervisor-logs"),
    path("supervisor/reports/", SupervisorReportsView.as_view(), name="supervisor-reports"),
    path("supervisor/logs/<uuid:log_id>/", SupervisorLogDetailView.as_view(), name="supervisor-log-detail"),
    path("supervisor/logs/bulk-status/", SupervisorBulkStatusView.as_view(), name="supervisor-bulk-status"),
    path("supervisor/appraisals/", SupervisorAppraisalListView.as_view(), name="supervisor-appraisal-list"),
    path("supervisor/appraisals/<uuid:appraisal_id>/", SupervisorAppraisalDetailView.as_view(), name="supervisor-appraisal-detail"),
    path("admin/companies/", AdminCompanyListCreateView.as_view(), name="admin-companies"),
    path("admin/companies/<uuid:company_id>/", AdminCompanyDetailView.as_view(), name="admin-company-detail"),
    path("admin/company-requests/", AdminCompanyRequestListView.as_view(), name="admin-company-requests"),
    path("admin/company-requests/<uuid:request_id>/", AdminCompanyRequestDetailView.as_view(), name="admin-company-request-detail"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/students/", AdminStudentsView.as_view(), name="admin-students"),
    path("admin/students/<uuid:student_id>/", AdminStudentDetailView.as_view(), name="admin-student-detail"),
    path("admin/reports/", AdminReportsIndexView.as_view(), name="admin-reports-index"),
    path("admin/reports/<uuid:report_id>/", AdminReportDetailView.as_view(), name="admin-report-detail"),
    path("admin/reports/<uuid:report_id>/download/", AdminReportDownloadView.as_view(), name="admin-report-download"),
    path("admin/reports/<uuid:report_id>/preview/", AdminReportPreviewView.as_view(), name="admin-report-preview"),
    path("admin/appraisals/<uuid:appraisal_id>/", AdminAppraisalDetailView.as_view(), name="admin-appraisal-detail"),
]
