from django.urls import path

from .views import (
    AuthLoginView,
    AuthRegisterView,
    ChangePasswordView,
    GenerateReportView,
    HealthCheckView,
    StudentDashboardView,
    StudentGenerateReportView,
    StudentInternshipView,
    StudentReportsView,
    StudentFeedbackView,
    StudentLogDetailView,
    StudentLogView,
    StudentProfileView,
    StudentReportDraftView,
    SupervisorAppraisalDetailView,
    SupervisorAppraisalListView,
    SupervisorAssignedAppraisalStudentsView,
    SupervisorBulkStatusView,
    SupervisorLogDetailView,
    SupervisorLogsView,
    SupervisorReportsView,
    SupervisorStudentsView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("generate-report/", GenerateReportView.as_view(), name="generate-report"),
    path("auth/register/", AuthRegisterView.as_view(), name="auth-register"),
    path("auth/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="auth-change-password"),
    path("student/profile/", StudentProfileView.as_view(), name="student-profile"),
    path("student/dashboard/", StudentDashboardView.as_view(), name="student-dashboard"),
    path("student/reports/", StudentReportsView.as_view(), name="student-reports"),
    path("student/internships/", StudentInternshipView.as_view(), name="student-internships"),
    path("student/logs/", StudentLogView.as_view(), name="student-logs"),
    path("student/logs/<uuid:log_id>/", StudentLogDetailView.as_view(), name="student-log-detail"),
    path("student/feedbacks/", StudentFeedbackView.as_view(), name="student-feedbacks"),
    path("student/report-draft/", StudentReportDraftView.as_view(), name="student-report-draft"),
    path("student/generate-report/", StudentGenerateReportView.as_view(), name="student-generate-report"),
    path("supervisor/students/", SupervisorStudentsView.as_view(), name="supervisor-students"),
    path("supervisor/appraisal-students/", SupervisorAssignedAppraisalStudentsView.as_view(), name="supervisor-appraisal-students"),
    path("supervisor/logs/", SupervisorLogsView.as_view(), name="supervisor-logs"),
    path("supervisor/reports/", SupervisorReportsView.as_view(), name="supervisor-reports"),
    path("supervisor/logs/<uuid:log_id>/", SupervisorLogDetailView.as_view(), name="supervisor-log-detail"),
    path("supervisor/logs/bulk-status/", SupervisorBulkStatusView.as_view(), name="supervisor-bulk-status"),
    path("supervisor/appraisals/", SupervisorAppraisalListView.as_view(), name="supervisor-appraisal-list"),
    path("supervisor/appraisals/<uuid:appraisal_id>/", SupervisorAppraisalDetailView.as_view(), name="supervisor-appraisal-detail"),
]
